language: dart
dart:
  - dev

dart_task:
  - dartanalyzer: --fatal-warnings lib

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install lcov

script:
  - pub run test -r expanded test/*.dart
  - pub get
  - pub global activate coverage
  - dart --pause-isolates-on-exit --enable-vm-service=8111 test/test_all.dart &
  - sleep 1
  - pub global run coverage:collect_coverage --uri=http://127.0.0.1:8111/ -o coverage.json --resume-isolates
  - pub global run coverage:format_coverage --packages=.packages -i coverage.json -o coverage.lcov --lcov --report-on=lib/

after_success:
  - pub global run coveralls coverage.lcov
  - bash <(curl -s https://codecov.io/bash)
