name: units
description: A starting point for measurement units in Dart.
version: 0.0.6
homepage: https://github.com/yeradis/units.dart
author: Yeradis P. Barbosa Marrero <yeradis@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
